#!/usr/bin/env bash

rm -rf \
Makefile.in \
aclocal.m4 \
m4/* \
autom4te.cache \
autoscan.log \
.config* \
config.cache \
config.guess \
config.h \
config.h.in \
config.h.in~ \
config.log \
config.status \
config.sub \
configure \
configure.scan \
depcomp.lnk \
install-sh.lnk \
missing.lnk \
depcomp \
install-sh \
libtool \
ltmain.sh \
missing \
mkinstalldirs \
stamp-h1 \
Makefile \
*.la \
*.lo \
*.a \
*.o \
Makefile \
Makefile.in \
.deps \
.libs \
COPYING \
INSTALL
if [ `which libtoolize | awk '{print $1}' | grep -c libtoolize` != 0 ]; then
	libtoolize
else
	glibtoolize
fi
aclocal
autoconf
automake --add-missing
