#!/usr/bin/env bash

rm -rf \
Makefile.in \
aclocal.m4 \
m4/* \
autom4te.cache \
autoscan.log \
.config* \
config.cache \
config.guess \
config.h \
config.h.in \
config.h.in~ \
config.log \
config.status \
config.sub \
configure \
configure.scan \
depcomp.lnk \
install-sh.lnk \
missing.lnk \
depcomp \
install-sh \
libtool \
ltmain.sh \
missing \
mkinstalldirs \
stamp-h1 \
Makefile \
src/test.* \
src/test \
src/*.la \
src/*.lo \
src/*.a \
src/*.o \
src/open3dqsar \
src/open3dqsar.exe \
`find doc -name Makefile` \
`find doc -name Makefile.in` \
`find doc -name .deps` \
`find doc -name .libs` \
`find example -name Makefile` \
`find example -name Makefile.in` \
`find example -name .deps` \
`find example -name .libs` \
`find src -name Makefile` \
`find src -name Makefile.in` \
`find src -name .deps` \
`find src -name .libs` \
`find test -name Makefile` \
`find test -name Makefile.in` \
`find test -name .deps` \
`find test -name .libs` \
`find util -name Makefile` \
`find util -name Makefile.in` \
`find util -name .deps` \
`find util -name .libs`
if [ `which libtoolize | awk '{print $1}' | grep -c libtoolize` != 0 ]; then
	libtoolize
else
	glibtoolize
fi
aclocal -I m4
autoheader
autoconf
automake --add-missing
